/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from the docs directory structure
    },
  ],
};

export default sidebars;
